name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: windows-latest
    environment:
      name: pypi
      url: https://pypi.org/p/sigcoeff
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install Cython numba numpy
      - name: Build Cython extensions
        run: |
          python setup.py build_ext --inplace
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
      - name: Verify package
        run: |
          python -m twine check dist/*
      - name: Publish package distributions to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload --non-interactive dist/*